// Usage: make optmize-cse
/**
 * Almost all comments are generated by GitHub Copilot
 */
#include "llvm/Support/raw_ostream.h"
#include "llvm/ADT/Statistic.h"

#include "UnitCSE.h"

#define DEBUG_TYPE "UnitCSE"
// Define any statistics here

using namespace llvm;
using namespace cs426;

#include <set>


PreservedAnalyses UnitCSE::run(Function &F, FunctionAnalysisManager &FAM) {
    // Get the necessary analyses
    DominatorTree &DT = FAM.getResult<DominatorTreeAnalysis>(F);
    AliasAnalysis &AA = FAM.getResult<AAManager>(F);

    dbgs() << "UnitCSE running on " << F.getName() << "\n";

    bool Changed = false;

    return Changed ? PreservedAnalyses::none() : PreservedAnalyses::all();
}
